# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(default='AJAY', max_length=100)),
                ('LAST_NAME', models.TextField(default='Kuril', max_length=100)),
            ],
            options={
                'ordering': ('FIRST_NAME',),
            },
        ),
    ]
