# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pat',
            options={'ordering': ('user_name',)},
        ),
        migrations.RemoveField(
            model_name='pat',
            name='FIRST_NAME',
        ),
        migrations.RemoveField(
            model_name='pat',
            name='LAST_NAME',
        ),
        migrations.AddField(
            model_name='pat',
            name='user_email',
            field=models.TextField(default='Blank2', max_length=100),
        ),
        migrations.AddField(
            model_name='pat',
            name='user_name',
            field=models.CharField(default='Blank', max_length=100),
        ),
        migrations.AddField(
            model_name='pat',
            name='user_password',
            field=models.TextField(default='None', max_length=100),
        ),
    ]
