# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170324_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pat',
            name='user_name',
            field=models.CharField(default='Blank', max_length=100),
        ),
    ]
